### ISSUE TITLE
[Question] Fail when uploading same file

### ISSUE THREAD

**Issue by bagusnl** [ryand56/r2-upload-action#217] opened 2023-07-04 06:06 UTC
Hi!
First of all, thank you so much for this GitHub action you've made!

I'm trying to set up a CDN for an app that me and some other people working with so it can use Cloudflare R2 for updates and such. All of our stuff is currently on a GitHub repo and we need a way to upload it all to R2, so I tried to use your action script.
On the first run it works flawlessly! Everything work and all the files shows up where it needs to be. Though, on the second run, it fails with error code `R2 Error - At least one of the pre-conditions you specified did not hold.`, and with a bit of searching I couldn't find what this error code means, but I think its because the file already exist in the bucket.

Is there a way to make the action always overwrite the file in the bucket or some way to clean all the bucket directories first before running the action?

Thank you

**Comment by ryand56** [comment] 2023-07-05 05:33
Hi, it should overwrite the file, but I'll do some testing tonight and see if I can reproduce the issue.

**Comment by bagusnl** [comment] 2023-07-05 07:22
Thank you for responding, I forgot to add some of my details they are

As a note 
- Repository in question
> https://github.com/bagusnl/CollapseLauncher-ReleaseRepo/tree/main

- Failed action log
https://github.com/bagusnl/CollapseLauncher-ReleaseRepo/actions/runs/5451242413/jobs/9917344005

- Frontend for the R2 bucket
https://r2-render.bagelnl.my.id/

**Comment by ryand56** [comment] 2023-07-05 22:51
Well, looks like I have found the issue, the ETag in the file being uploaded has to be different. So, you can't upload the same files over and over again.

**Comment by ryand56** [comment] 2023-07-05 23:28
Should be fixed in commit 70fb64e02a7282737f3c08892e6f9c5e5d5e9e7d! I'll release a new version momentarily.

**Closed by ryand56** 2023-07-05 23:28 UTC
Labels: bug, verified

**Comment by bagusnl** [comment] 2023-07-06 00:17
Thank you for the fix!
