### ISSUE TITLE
Syncing to Cloudflare R2 will still automatically create a "/" folder

### ISSUE THREAD

**Issue by koobai** [ryand56/r2-upload-action#266] opened 2023-08-09 01:15 UTC
1. the latest version is used, if "destination-dir" is not defined, the upload to Cloudflare R2 will still automatically create a "/" folder, but not to the root directory.
2. The Github repository deletes files, Cloudflare R2 will not delete them. It would be nice to keep the same structure as the Gtihub file
<img width="856" alt="image" src="https://github.com/ryand56/r2-upload-action/assets/50470569/15ffaeef-40a3-4044-bbb5-dd00780d364b">

**Comment by ryand56** [comment] 2023-08-09 03:17
Hello, it is working for me so I don't know what the issue is

**Comment by ryand56** [comment] 2023-08-09 03:31
As for the second question, that's not the purpose of this action. It is to update contents in an R2 bucket and not change the entire structure. You can do that manually with the R2 UI.

**Comment by koobai** [comment] 2023-08-09 04:31
Thank you for your reply, I don't know why the "/" folder is automatically added
<img width="466" alt="image" src="https://github.com/ryand56/r2-upload-action/assets/50470569/a9d31417-467d-4f93-955e-9910871cf602">

Here are my Actions
<img width="753" alt="image" src="https://github.com/ryand56/r2-upload-action/assets/50470569/7ccde92d-3f49-4262-8608-3cb5b865854f">

**Comment by ryand56** [comment] 2023-08-09 08:09
Fixed in #267 and released new version

**Closed by ryand56** 2023-08-09 08:09 UTC
